"""collect columns and runs

Revision ID: 8bf70b53af4f
Revises: 264839ae4c6d
Create Date: 2026-09-30 16:23:41.821334

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8bf70b53af4f"
down_revision: str | Sequence[str] | None = "264839ae4c6d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collect_runs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("job", sa.Text(), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "detail",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('running', 'success', 'partial', 'failed', 'skipped')",
            name=op.f("ck_collect_runs_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collect_runs")),
    )
    op.create_index(
        "ix_collect_runs_job_trade_date", "collect_runs", ["job", "trade_date"], unique=False
    )
    op.add_column(
        "investor_trading_daily",
        sa.Column("source", sa.Text(), server_default=sa.text("'toss'"), nullable=False),
    )
    op.alter_column(
        "investor_trading_daily", "individual_net", existing_type=sa.BIGINT(), nullable=True
    )
    op.add_column("stocks", sa.Column("security_type", sa.Text(), nullable=True))
    op.add_column(
        "stocks",
        sa.Column(
            "trading_suspended", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column(
        "stocks",
        sa.Column(
            "liquidation_trading", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column(
        "stocks", sa.Column("source", sa.Text(), server_default=sa.text("'toss'"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stocks", "source")
    op.drop_column("stocks", "liquidation_trading")
    op.drop_column("stocks", "trading_suspended")
    op.drop_column("stocks", "security_type")
    op.alter_column(
        "investor_trading_daily", "individual_net", existing_type=sa.BIGINT(), nullable=False
    )
    op.drop_column("investor_trading_daily", "source")
    op.drop_index("ix_collect_runs_job_trade_date", table_name="collect_runs")
    op.drop_table("collect_runs")
    # ### end Alembic commands ###
