"""initial schema

Revision ID: 4c1b16e31441
Revises:
Create Date: 2026-09-30 13:54:33.146556

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4c1b16e31441"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts_sent",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("dedupe_key", sa.Text(), nullable=False),
        sa.Column("channel", sa.Text(), nullable=False),
        sa.Column(
            "sent_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts_sent")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_alerts_sent_dedupe_key")),
    )
    op.create_table(
        "api_tokens",
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("access_token", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("provider", name=op.f("pk_api_tokens")),
    )
    op.create_table(
        "asset_snapshots",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("market_value", sa.BigInteger(), nullable=False),
        sa.Column("cash", sa.BigInteger(), nullable=False),
        sa.Column("total", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("date", name=op.f("pk_asset_snapshots")),
    )
    op.create_table(
        "candles_daily",
        sa.Column("symbol", sa.Text(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("open", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("high", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("low", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("close", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.Column("adjusted", sa.Boolean(), nullable=False),
        sa.Column("source", sa.Text(), server_default=sa.text("'toss'"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("symbol", "date", name=op.f("pk_candles_daily")),
    )
    op.create_table(
        "cash_flows",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("amount", sa.BigInteger(), nullable=False),
        sa.Column("memo", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cash_flows")),
    )
    op.create_index(op.f("ix_cash_flows_date"), "cash_flows", ["date"], unique=False)
    op.create_table(
        "holding_alert_state",
        sa.Column("symbol", sa.Text(), nullable=False),
        sa.Column("avg_price", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("last_band", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("symbol", name=op.f("pk_holding_alert_state")),
    )
    op.create_table(
        "investor_trading_daily",
        sa.Column("symbol", sa.Text(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("foreigner_net", sa.BigInteger(), nullable=False),
        sa.Column("institution_net", sa.BigInteger(), nullable=False),
        sa.Column("individual_net", sa.BigInteger(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("symbol", "date", name=op.f("pk_investor_trading_daily")),
    )
    op.create_table(
        "robots",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("style", sa.Text(), nullable=False),
        sa.Column("holding_period", sa.Text(), nullable=False),
        sa.Column("risk_level", sa.Text(), nullable=False),
        sa.Column(
            "params",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "enabled_globally", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.CheckConstraint(
            "risk_level IN ('low', 'medium', 'high')", name=op.f("ck_robots_risk_level")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_robots")),
    )
    op.create_table(
        "stocks",
        sa.Column("symbol", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("market", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("is_common_share", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("list_date", sa.Date(), nullable=True),
        sa.Column("delist_date", sa.Date(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("symbol", name=op.f("pk_stocks")),
    )
    op.create_table(
        "backtest_runs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("robot_id", sa.Text(), nullable=False),
        sa.Column(
            "params",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("split_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "metrics",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["robot_id"], ["robots.id"], name=op.f("fk_backtest_runs_robot_id_robots")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backtest_runs")),
    )
    op.create_table(
        "robot_settings",
        sa.Column("robot_id", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["robot_id"], ["robots.id"], name=op.f("fk_robot_settings_robot_id_robots")
        ),
        sa.PrimaryKeyConstraint("robot_id", name=op.f("pk_robot_settings")),
    )
    op.create_table(
        "signals",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("robot_id", sa.Text(), nullable=False),
        sa.Column("symbol", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'OPEN'"), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("target_price", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("stop_price", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("close_price", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("return_pct", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column(
            "reason",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "source IN ('live', 'backtest', 'paper')", name=op.f("ck_signals_source")
        ),
        sa.CheckConstraint(
            "status IN ('OPEN', 'TAKE_PROFIT', 'STOP_LOSS', 'EXPIRED', 'CANCELLED')",
            name=op.f("ck_signals_status"),
        ),
        sa.ForeignKeyConstraint(
            ["robot_id"], ["robots.id"], name=op.f("fk_signals_robot_id_robots")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signals")),
    )
    op.create_index("ix_signals_status_opened_at", "signals", ["status", "opened_at"], unique=False)
    op.create_index(
        "uq_signals_one_open_per_robot_symbol",
        "signals",
        ["robot_id", "symbol", "source"],
        unique=True,
        postgresql_where=sa.text("status = 'OPEN'"),
    )
    op.create_table(
        "watchlists",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("robot_id", sa.Text(), nullable=False),
        sa.Column("symbol", sa.Text(), nullable=False),
        sa.Column("score", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column(
            "reason",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["robot_id"], ["robots.id"], name=op.f("fk_watchlists_robot_id_robots")
        ),
        sa.PrimaryKeyConstraint("date", "robot_id", "symbol", name=op.f("pk_watchlists")),
    )
    op.create_table(
        "backtest_trades",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.BigInteger(), nullable=False),
        sa.Column("symbol", sa.Text(), nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("exit_date", sa.Date(), nullable=True),
        sa.Column("exit_price", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("return_pct", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("exit_reason", sa.Text(), nullable=True),
        sa.Column("segment", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["backtest_runs.id"],
            name=op.f("fk_backtest_trades_run_id_backtest_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backtest_trades")),
    )
    op.create_index(op.f("ix_backtest_trades_run_id"), "backtest_trades", ["run_id"], unique=False)
    op.create_table(
        "paper_positions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("signal_id", sa.UUID(), nullable=False),
        sa.Column("qty", sa.BigInteger(), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("exit_price", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("pnl", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column(
            "opened_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["signal_id"], ["signals.id"], name=op.f("fk_paper_positions_signal_id_signals")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_paper_positions")),
        sa.UniqueConstraint("signal_id", name=op.f("uq_paper_positions_signal_id")),
    )
    op.create_table(
        "signal_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("signal_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("price", sa.Numeric(precision=20, scale=4), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signals.id"],
            name=op.f("fk_signal_events_signal_id_signals"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signal_events")),
    )
    op.create_index(
        op.f("ix_signal_events_signal_id"), "signal_events", ["signal_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_signal_events_signal_id"), table_name="signal_events")
    op.drop_table("signal_events")
    op.drop_table("paper_positions")
    op.drop_index(op.f("ix_backtest_trades_run_id"), table_name="backtest_trades")
    op.drop_table("backtest_trades")
    op.drop_table("watchlists")
    op.drop_index(
        "uq_signals_one_open_per_robot_symbol",
        table_name="signals",
        postgresql_where=sa.text("status = 'OPEN'"),
    )
    op.drop_index("ix_signals_status_opened_at", table_name="signals")
    op.drop_table("signals")
    op.drop_table("robot_settings")
    op.drop_table("backtest_runs")
    op.drop_table("stocks")
    op.drop_table("robots")
    op.drop_table("investor_trading_daily")
    op.drop_table("holding_alert_state")
    op.drop_index(op.f("ix_cash_flows_date"), table_name="cash_flows")
    op.drop_table("cash_flows")
    op.drop_table("candles_daily")
    op.drop_table("asset_snapshots")
    op.drop_table("api_tokens")
    op.drop_table("alerts_sent")
    # ### end Alembic commands ###
